import random

data = [
    "<classification>discussion</classification>\n\n<about>\nThe discussion is about whether OP tokens should be changed from a governance token to the main network token for gas payments on the Optimism network.\n</about>\n\n<first_post>\n- Proposes changing OP tokens from governance to main network token for gas fees\n- Seeks community agreement on the proposal\n</first_post>\n\n<reaction>\n- Some support the idea, believing it will benefit OP in the long term and increase its utility\n- Others argue it will complicate the system, as Optimism still needs to pay Ethereum fees in ETH\n- Concerns about losing Ethereum Equivalence and the added complexity of converting OP to ETH for L1 fees\n- Some believe governance tokens should remain for governance purposes only\n- A few users suggest the proposal is driven by short-term price gains rather than long-term benefits\n</reaction>\n\n<tldr>\nThis is an old thread and the information may be outdated. The community discusses whether OP tokens should be used for gas payments instead of governance, with mixed opinions on the benefits and drawbacks, including concerns about added complexity and maintaining Ethereum Equivalence.\n</tldr>"
    "<classification>announcement</classification>\n\n<about>\nThe thread is an announcement about the Working Constitution of the Optimism Collective, detailing its governance model and principles.\n</about>\n\n<overview>\n- Introduction to the Optimism Collective's Vision and governance experiment\n- Explanation of the Working Constitution as a temporary, experimental document\n- Bicameral governance system balancing OP Citizens and OP Holders\n- Role of the Optimism Foundation in early governance and stewardship\n- Rights and responsibilities of OP Citizens and OP Holders\n- Guiding principles for interpreting the Constitution, including governance minimization, forking, anti-plutocracy, and impact=profit\n- Encouragement to stay optimistic\n</overview>\n\n<reaction>\n- General excitement and support for the initiative\n- Questions about participation in governance activities and voting on proposals\n- Interest in the future role and influence of the Optimism Foundation\n- Curiosity about the balance between the two houses and handling gridlock decisions\n</reaction>\n\n<tldr>\nThis is an old thread and the information may be outdated. The thread announces the Working Constitution of the Optimism Collective, outlining its experimental governance model, the roles of OP Citizens and OP Holders, and the stewardship of the Optimism Foundation. The community shows excitement and curiosity about participation and future developments.\n</tldr>",
    "<classification>informative</classification>\n\n<about>\nThe thread provides detailed information about the nomination process for the second round of Retroactive Public Goods Funding (RetroPGF2) by Optimism.\n</about>\n\n<overview>\n- Kick-off for project nominations for RetroPGF2\n- Timeline: Nominations (Jan 17 - Jan 31, 2023), Final opt-in (Feb 21, 2023), Voting (Mar 7 - Mar 21, 2023)\n- 10 million OP tokens to be distributed to public goods supporting the OP Stack\n- Categories: Infrastructure + Dependencies, Tooling + Utilities, Education\n- Nomination process: Submit projects in relevant forum posts, avoid duplicate nominations, and ensure project profiles are complete and verified\n- Projects must opt-in and complete profiles by Feb 21, 2023\n- Community feedback is encouraged and a retrospective will be held post-round\n- Important links: [RetroPGF2 Governance Documentation](https://community.optimism.io/docs/governance/retropgf-2/#), [Project Manual](https://www.notion.so/oplabs/Optimism-RetroPGF-2-Project-Manual-0a2e741133cd49b0b005ff759934b998), [Discord Channel](https://discord.gg/3UZeg3cY)\n</overview>\n\n<tldr>\nThis is an old thread and the information may be outdated. The thread provides detailed instructions for nominating projects for the second round of Retroactive Public Goods Funding (RetroPGF2) by Optimism, including timelines, categories, and the nomination process. 10 million OP tokens will be distributed to public goods supporting the OP Stack.\n</tldr>",
]


def get_sample_summary():
    return random.choice(data)
